version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-southeast-2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - echo "Installing cfn-lint"
      - pip install cfn-lint
      - echo "Installing taskcat"
      - pip install taskcat

  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Checking tool versions"
      - python --version
      - pip --version
      - aws --version
      - cfn-lint --version
      - taskcat --version
      - echo "Validating file structure..."
      - ls -la
      - ls -la cloudformation/ || echo "Warning - cloudformation directory not found"
      - echo "Checking if CloudFormation template exists"
      - |

  build:
    commands:
      - echo "Build phase started on $(date)"
      - echo "=== Running cfn-lint validation ==="
      - cfn-lint cloudformation/template.yml
      - |
        if [ $? -eq 0 ]; then
          echo "cfn-lint validation passed"
        else
          echo "cfn-lint validation failed"
          exit 1
        fi
      - echo "=== Running AWS CloudFormation template validation ==="
      - aws cloudformation validate-template --template-body file://cloudformation/template.yml
      - |
        if [ $? -eq 0 ]; then
          echo "AWS CloudFormation template validation passed"
        else
          echo "AWS CloudFormation template validation failed"
          exit 1
        fi
      - echo "=== Running taskcat tests ==="
      - cd cloudformation
      - |
        if taskcat test run --no-delete 2>&1 | tee ../taskcat-output.log; then
          echo "Taskcat tests completed successfully"
          taskcat test clean ALL || echo "Warning - Some taskcat cleanup may have failed"
        else
          echo "Taskcat tests failed"
          echo "Taskcat output:"
          cat ../taskcat-output.log
          taskcat test clean ALL || echo "Warning - Taskcat cleanup failed"
          exit 1
        fi
      - cd ..

  post_build:
    commands:
      - echo "Post-build phase started on $(date)"
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" = "1" ]; then
          echo "Build completed successfully"
          echo "All validation checks passed:"
          echo "  - cfn-lint validation: OK"
          echo "  - AWS template validation: OK"
          echo "  - Taskcat testing: OK"
        else
          echo "Build failed"
          echo "Please check the build logs above for details"
        fi
      - echo "Build phase completed on $(date)"

reports:
  taskcat-report:
    files:
      - cloudformation/taskcat_outputs/**/*
    base-directory: '.'

artifacts:
  files:
    - cloudformation/template.yml
    - cloudformation/.taskcat.yml
    - cloudformation/taskcat_outputs/**/*
    - taskcat-output.log
  name: cloudformation-validated-artifacts

cache:
  paths:
    - '/root/.cache/pip/**/*'