name: Sync to AWS CodeCommit

on:
    push:
        branches:
            - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 

      - name: Push to CodeCommit
        run: |
            git config --global user.email "giabaoctg@gmail.com"
            git config --global user.name "xyan-dhgb"
            git remote add codecommit https://$CODECOMMIT_USERNAME:$CODECOMMIT_PASSWORD@git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/your-repo
            git push --force codecommit main
    env:
        CODECOMMIT_USERNAME: ${{ secrets.CODECOMMIT_USERNAME }}
        CODECOMMIT_PASSWORD: ${{ secrets.CODECOMMIT_PASSWORD }}
