# Name of the workflow
name: Checkov Terraform and Deploy to AWS

# Trigger the workflow on push to the main branch
on:
  push:
    branches: [main]
    paths:
      - 'aws-infr/**'
  pull_request:
    branches: [man]
    paths:
      - 'aws-infr/**'

# Give perrsions to read the workflow
permissions:
  contents: read

env:
  TF_WORKING_DIR: ./aws-infr

# Define the jobs that will run in this workflow
jobs:
  checkov:
    name: Check security scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov scan
        run: |
          checkov -d $TF_WORKING_DIR --quiet

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.0

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
        
        # Optional: Check if aws-infr/ folder has changed
      - name: Check if aws-infr/ folder has changed  
        id: folder_check_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^aws-infr/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Init
        if: steps.folder_check_changes.outputs.changed == 'true'
        run: terraform init
        working-directory: ${{env.TF_WORKING_DIR}}

      - name: Terraform Validate
        if: steps.folder_check_changes.outputs.changed == 'true'
        run: terraform validate
        working-directory: ${{env.TF_WORKING_DIR}}

      - name: Terraform Plan
        if: steps.folder_check_changes.outputs.changed == 'true'
        run: terraform plan -var-file="terraform.tfvars"
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        if: github.event_name == 'push' && steps.folder_check_changes.outputs.changed == 'true'
        run: terraform apply -auto-approve
        working-directory: ${{env.TF_WORKING_DIR}}