# Name of the workflow
name: Checkov Terraform and Deploy to AWS

# Trigger the workflow on push to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [man]

# Give perrsions to read the workflow
permissions:
  contents: read

env:
  TF_WORKING_DIR: ./aws-infr

# Define the jobs that will run in this workflow
jobs:
  checkov:
    name: Check security scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov scan
        run: |
          checkov -d $TF_WORKING_DIR --quiet

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.0

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2


      - name: Terraform Init
        run: terraform init
        working-directory: ${{env.TF_WORKING_DIR}}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{env.TF_WORKING_DIR}}
      
      - name: Terraform Plan
        run: terraform plan -var="ami_id=ami-0f5d1713c9af4fe30" -var="key_name=lab2-ssh-key-pair"
        working-directory: ${{env.TF_WORKING_DIR}}

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="ami_id=ami-0f5d1713c9af4fe30" -var="key_name=lab2-ssh-key-pair"
        working-directory: ${{env.TF_WORKING_DIR}}